# Site settings
title: Loading Screen Solutions
author:
  name: James Miller
  email: james@loadingscreensolutions.com
description: "Digital Independence"

# Build settings
remote_theme: jekyll/slate
